name: elomda
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator:
  carousel_pro:
  shared_preferences:
  dio:
  flutter_icons:
  bloc: ^8.0.2
  image_picker: ^0.8.4+10
  flutter_bloc: ^8.0.1
  backdrop: ^0.7.1
  flutter_svg: ^1.0.3
  rounded_loading_button: ^2.0.9
  google_fonts: ^2.3.1
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.7
  google_sign_in: ^5.2.4
  firebase_storage: ^10.2.9
  flutter_easyloading: ^3.0.3
  flutter_staggered_grid_view: ^0.6.1
  dropdown_search: ^2.0.1
  dropdown_button2: ^1.2.2
  badges: ^2.0.2
  cart_stepper: ^2.0.2
  firebase_messaging: ^11.2.8
  flutter_slidable: ^1.2.0
  flutter_conditional_rendering: ^2.0.0
  list_tile_switch:
  url_launcher: ^6.0.0
  pin_code_fields: ^7.4.0
  hexcolor: ^2.0.0
  flutter_countdown_timer: ^4.1.0
  responsive_grid_list: ^1.2.4
  assets_audio_player: ^3.0.4+1
  flutter_smart_dialog: ^3.4.2+2
  double_back_to_close_app: ^2.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true


  assets:
     - assets/
     - assets/audios/




  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

