name: elomda
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  smooth_page_indicator:
  carousel_pro:
  shared_preferences:
  dio:
  flutter_icons:
  bloc: ^8.0.2
  image_picker: ^1.0.4
  flutter_bloc: ^8.0.1
  backdrop: ^0.9.1
  flutter_svg: ^2.0.5
  rounded_loading_button: ^2.0.9
  google_fonts: ^4.0.4
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  firebase_storage: ^11.2.6
  flutter_easyloading: ^3.0.3
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^5.0.6
  dropdown_button2: ^2.1.4
  badges: ^3.1.1
  cart_stepper: ^4.1.2
  firebase_messaging: ^14.6.7
  flutter_slidable: ^3.0.0
  flutter_conditional_rendering: ^2.0.0
  list_tile_switch:
  url_launcher: ^6.0.0
  pin_code_fields: ^8.0.1
  hexcolor: ^3.0.1
  flutter_countdown_timer: ^4.1.0
  responsive_grid_list: ^1.2.4
  assets_audio_player: ^3.0.4+1
  flutter_smart_dialog: ^4.9.4
  double_back_to_close_app: ^2.1.0
  intl: ^0.18.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.3


flutter:


  uses-material-design: true


  assets:
     - assets/
     - assets/images/
     - assets/icons/
     - assets/audios/




  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-SemiBold.ttf
        - asset: fonts/Poppins-Bold.ttf
    - family: IconBroken
      fonts:
        - asset: assets/fonts/icons.ttf

